### ISSUE TITLE
Request for version 1.1.1 in Cura Marketplace

### ISSUE THREAD

**Issue by seantapscott** [fieldOfView/Cura-ArcWelderPlugin#13]
There's a bugfix version of the ArcWelder plugin (v1.1.1) available [here](https://github.com/FormerLurker/ArcWelderLib/releases/tag/1.1.1) . 

My current version seems to still be using 1.1.0 (discovered using arcwelder.exe -h ).  

Would you be willing to push a new version into the cura marketplace?  

Please and thanks. :)

**Comment by fieldOfView** [comment]
The next version of the plugin will include ArcWelder 1.1.1 or newer. I have been told by @FormerLurker that the 1.1.1 update was probably not all that relevant for Cura, which is why I have not yet put much effort into that.

**Comment by fieldOfView** [comment]
I have updated the binaries in commit 2c9ebb3f3fe31efdf7b80e9e04c51e117fcbd77b, but will keep this issue open until a new release is available in the Marketplace

**Comment by seantapscott** [comment]
Thank you.  I have been reading some of the issues that users are having,
and some of them do seem relevant.

Thanks again.

**Comment by FormerLurker** [comment]
@seantapscott, one fairly major bug was fixed in 1.1.1, but it seemed pretty rare.  It was related to whitespace between G1s that were converted into arcs.  It was a pretty rare situation.

The only issue I can't seem to track down is why some users have slowdowns when printing infill.  I believe that might be a firmware problem, but I've received enough gcode samples now to figure this out.  I'm suspecting that some firmware doesn't properly handle feedrate changes done with G2/G3, but will need to confirm that.

Thanks @fieldOfView for keeping things updated!  The algorithm is starting to mature, and I expect the release frequency to decrease.
