### ISSUE TITLE
Arc Conversion Performance

### ISSUE THREAD

**Issue by Snoman002** [fieldOfView/Cura-ArcWelderPlugin#32]
Cura 5.2.1
ArcWelder 3.6
Ender 3 v1

In using arcwelder and looking at total performance there appeared to be a significant amount of G0 moves that could have (should have) been converted to arcs.  you can see this in a designed part that is almost exclusivly circles.  
-Top and bottom patterns are "concentric" in this case and the vast majority of the part should be arcs.
-Resolution was increased from .05 to .5 and path tolerance from 5% to 10%.  The number of arcs improved significantly but obviously not completely.
-Part constructed in Solidworks and exported in a very high resolution STL (15MB)

You can visualize this in ncviewer.com (blue appears to be arcs, orange appears to be g0 commands)
![image](https://user-images.githubusercontent.com/62316078/207469405-f36150fb-3f1f-4f08-aa5d-78335f372fd3.png)

[Arc Test 2.zip](https://github.com/fieldOfView/Cura-ArcWelderPlugin/files/10222962/Arc.Test.2.zip)

**Comment by Jay-Ti** [comment]
Bumping This Issue since I'm running into the same Problem.

Printer Supports G2/G3 tested via manual Gcode command
I'm printing a single wall cylinder thickness= nozzle size=layer width.
With 300 G2/G3 commands out of 30,000 G1 Commands.  So 1% of the whole circular part.

Played around with the settings but yielded no better results.
Same on Cura 5.0 and 5.6

**Comment by fieldOfView** [comment]
This plugin is just glue between Cura and ArcWelder. For issues with ArcWelder itself, see https://github.com/FormerLurker/ArcWelderLib
